landing-news-posts: 2
landing-pubs: 5

landing-software:
 - panacus
 - pangenie
 - graphaligner
 - mbg
 - panpa
 - whatshap

person-page-posts: 4
person-page-projects: 4
person-page-pubs: 4

pub-author-limit: 75
